name: "Build artifact"
on: release

jobs:
  buildForLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneLinux64
      - uses: actions/upload-artifact@v2
        with:
          name: Build-StandaloneLinux64
          path: build/StandaloneLinux64
